### ISSUE TITLE
Shiplist Martyr (1.0.1)

### ISSUE THREAD

**Issue by Tjoosten** [Tjoosten/ion-auh-docs-tweak#3]
- [ ] #1 Setup active state
- [x] #2 Adding contributing file.
- [ ] #4 Enable syntax highlighting.
- [ ] Rebase the project repository.
